### ISSUE TITLE
Support config options instead of configFile location

### ISSUE THREAD

**Issue by otakustay** [cascornelissen/stylelint-bare-webpack-plugin#6]
In our team we encapsulated stylelint's config in a CLI tool, as a result we don't have a standalone `stylelintrc` file, the only thing we can provide to this plugin is a config object, is it possible to make this plugin accepting this object as config?

**Comment by cascornelissen** [comment]
Feels like a valid use case, this might go great together with #4. I’m quite busy the coming few weeks but you’re free to submit a PR!

**Comment by cascornelissen** [comment]
@otakustay, I've just checked this out and it seems like that should already be possible by just passing a `config` option to this plugin. I've just added a snippet to the documentation to make this a little clearer in commit https://github.com/cascornelissen/stylelint-bare-webpack-plugin/commit/2ffa8892d46fe9655658b3b22d2dd02690cb1f50.
