### ISSUE TITLE
support 'lintDirtyModulesOnly' option

### ISSUE THREAD

**Issue by o2dazone** [cascornelissen/stylelint-bare-webpack-plugin#7]
I moved over from `stylelint-webpack-plugin` to this.

It's a fantastic substitution, with my only complaint being it does not support the `lintDirtyModulesOnly` boolean from the other package. This makes my increment dev hot reloads go from < 1 second to 5-8 seconds.

https://www.npmjs.com/package/stylelint-webpack-plugin#lintdirtymodulesonly

https://github.com/webpack-contrib/stylelint-webpack-plugin/blob/master/lib/lint-dirty-modules-plugin.js

**Comment by cascornelissen** [comment]
Feels like a feature that could be added to this plugin as well, I'm pretty busy the coming few weeks so I won't have time to work on it but you're free to submit a PR :v:
